### ISSUE TITLE
Train Data is unavailable

### ISSUE THREAD

**Issue by peylnog** [jeya-maria-jose/TransWeather#1]
Thanks for your excellent work.

But the train data you provided is unavailable now. Please check your file at [link](https://drive.google.com/file/d/1UlW_DlnT8oynWWIIJBjv11FeQxnIqwVW/view).

Have a good day

**Comment by ddghjikle** [comment]
The same issue. Could you please tackle this issue as soon as possible. Thanks  a lot!

**Comment by jeya-maria-jose** [comment]
Thank you for pointing it out. The link has been updated. New [Link].(https://drive.google.com/file/d/1tfeBnjZX1wIhIFPl6HOzzOKOyo0GdGHl/view)
